# Generated by Django 5.2.6 on 2025-09-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KayaProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.BigIntegerField(db_index=True, unique=True)),
                ('submit_date', models.DateTimeField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_hourly', models.BooleanField(db_index=True, default=False)),
                ('budget_minimum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_maximum', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency_code', models.CharField(db_index=True, max_length=8)),
                ('has_attachment', models.BooleanField(default=False)),
                ('payment_verified', models.BooleanField(db_index=True, default=False)),
                ('owner_country', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_country_code', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('owner_city', models.CharField(blank=True, max_length=100, null=True)),
                ('freelancer_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jobs', models.ManyToManyField(blank=True, related_name='listings', to='KayaProjects.job')),
            ],
            options={
                'indexes': [models.Index(fields=['is_hourly', 'currency_code'], name='KayaProject_is_hour_b1456d_idx'), models.Index(fields=['payment_verified'], name='KayaProject_payment_82a3d0_idx'), models.Index(fields=['submit_date'], name='KayaProject_submit__808f01_idx')],
            },
        ),
    ]
