# Generated by Django 5.2.6 on 2025-09-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KayaProjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kayaproject',
            name='have_we_made_a_bid_on_it',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
