# Generated by Django 5.2.6 on 2025-09-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KayaProjects', '0002_kayaproject_have_we_made_a_bid_on_it'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kayaproject',
            name='have_we_made_a_bid_on_it',
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True),
        ),
    ]
