# Generated by Django 5.2.6 on 2025-09-12 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('KayaProjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KayaSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_minutes', models.PositiveIntegerField(default=10, help_text='Polling interval in minutes (must be ≥ 10).', validators=[django.core.validators.MinValueValidator(10)])),
                ('singleton_enforcer', models.BooleanField(default=True, editable=False, unique=True)),
                ('jobs', models.ManyToManyField(blank=True, related_name='kaya_settings', to='KayaProjects.job')),
            ],
        ),
    ]
