# Generated by Django 5.2.6 on 2025-09-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KayaSettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kayasetting',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
